require("core.config.lsp")
require("core.config.theme")
require("core.config.neotree")
require("core.config.trouble")
require("core.config.lualine")
require("core.config.telescope")
require("core.config.treesitter")
